name: Build and Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Hugo (Extended)
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.121.1'
          extended: true

      - name: Initialize Hugo Modules
        run: hugo mod tidy && hugo mod npm pack

      - name: Build site
        run: hugo --minify

      - name: Disable Jekyll
        run: touch public/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
